{
 "title": "Node Overview",
 "description": "Node Home Dashboard",
 "tags": [
  "Pigsty",
  "NODE",
  "Overview",
  "HOME"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Environment", "query": { "query": "label_values(node_load1, job)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_load1{job=\"$job\"}) by (ip))",
     "legendFormat": "Node"
    },
    {
     "expr": "node:env:cpu_count{job=\"$job\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "node:env:mem_total{job=\"$job\"}",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(node:env:size_bytes{job=\"$job\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:env:cpu_usage{job=\"$job\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:env:stdload1{job=\"$job\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:env:mem_usage{job=\"$job\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:env:space_usage{job=\"$job\"}",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node:cls:cpu_usage{}", "legendFormat": "{{ cls }}" }
   ]
  },
  {
   "type": "stat",
   "description": "Yellow : Node\n\nGreen: HAProxy\n\nRed: Promtail Logging Agent\n\nGreen: Docker\n\nPurple: Keepalived",
   "gridPos": { "h": 17, "w": 16, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_up{job=\"node\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "haproxy_up{job=\"node\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "promtail_up{job=\"node\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "docker_up{job=\"node\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "min by (job,cls,vip) (probe_success{job=\"node-vip\"})",
     "legendFormat": "{{ cls }} @ {{ vip }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"$job\"}) or on() vector(0)",
     "legendFormat": "Firing Alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"$job\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", job=\"$job\"}",
     "legendFormat": "[{{ severity }}] {{alertname}}  @ {{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Members",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Nodes",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 27 },
     "targets": [
      { "expr": "node_up{}" },
      {
       "expr": "group without(ins,cls,instance) (node_uname_info{})"
      },
      {
       "expr": "max by (ip) (node:ins:cpu_usage{})"
      },
      {
       "expr": "max by (ip) (node:ins:mem_usage{})"
      },
      {
       "expr": "sum by (ip,instance) (node:ins:space_usage_max{})"
      },
      {
       "expr": "max by (ip) (node:ins:cpu_count{}) "
      },
      {
       "expr": "max by (ip) (node_memory_MemTotal_bytes{}) / 1073741824"
      },
      {
       "expr": "sum(node:fs:size_bytes{}) by (ip) / 1073741824"
      },
      { "expr": "count by (ip) (up{ip!=''})" },
      {
       "expr": "max by (ip) (probe_duration_seconds{job=\"ping\"})"
      },
      {
       "expr": "sum by (ip) (haproxy_backend_current_sessions{})"
      },
      { "expr": "min by (ip) (node_up{})" },
      {
       "expr": "min by (ip) (node_timex_sync_status{})"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg_over_time(node:ins:cpu_usage{job=\"$job\"}[1m])",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Load 15",
     "type": "timeseries",
     "description": "Standard node load in last 15 minutes (divide by cpu core number)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg_over_time(node:ins:stdload15{job=\"$job\"}[1m])",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Memory usage ratio for each nodes:\n(total - avail) / total",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:mem_usage{job=\"$job\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Disk I/O RT (1m)",
     "type": "timeseries",
     "description": "Disk Read/Write Time Total / Disk IOPS in last minute",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "node:dev:disk_io_rt_1m{}", "legendFormat": "{{ ins }}-{{ device }}" }
     ]
    },
    {
     "title": "Disk IO Bandwidth",
     "type": "timeseries",
     "description": "total disk bandwidth per node",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node:ins:disk_io_bytes_rate1m{job=\"$job\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Network IO Rate1m",
     "type": "timeseries",
     "description": "total disk bandwidth per node",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node:ins:network_io_bytes_rate1m{job=\"$job\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Space Usage",
     "type": "stat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node:fs:space_usage{job=\"$job\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Ping RT",
     "type": "stat",
     "description": "Network RT in µs ",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_duration_seconds{job=\"ping\"}",
       "legendFormat": "{{ ins }} @ {{ ip }}"
      },
      {
       "expr": "avg by (job,vip) (probe_duration_seconds{job=~\".*vip\"})",
       "legendFormat": "{{ job }} @ {{ vip }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Proxy instances\n",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "sum by (ins,instance) (haproxy_server_current_sessions{})"
      }
     ]
    },
    {
     "type": "table",
     "description": "Services powered by this proxy instance",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 82 },
     "targets": [
      {
       "expr": "sum by (proxy) (haproxy_backend_current_sessions{proxy!=\"stats\"})"
      },
      {
       "expr": "sum by (proxy) (haproxy_server_status{})"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (proxy) (haproxy_backend_current_sessions{proxy!=\"stats\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service Health",
     "type": "state-timeline",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "sum by (cls,proxy) (haproxy_server_status{state=\"UP\"}) > bool 0",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  }
 ]
}